### PR TITLE
Added set_status job to update the PR with e2e status

### PR DESCRIPTION
**Pull request by MarkCalvert**

### CODE REVIEW

**Comment by MarkCalvert** [comment]
@tim-yao I have added a job to update the status at the end of the workflow which will show up in the PR checks.
Please review and let me know if this is what you expected or what information must be displayed.
Screenshot 2023-10-18 at 4 40 09 PM

**Comment by tim-yao** [comment]
> @tim-yao I have added a job to update the status at the end of the workflow which will show up in the PR checks. Please review and let me know if this is what you expected or what information must be displayed. Screenshot 2023-10-18 at 4 40 09 PM

Thanks @MarkCalvert. It looks nice. But how can we find the details from the PR status? It has no `details` link and is not in the PR checks. 

I can see it in the repo `Actions` list, but there is no way to know which one is for which PR, and I think directly checking in Actions is not a proper way for users.

**Comment by MarkCalvert** [comment]
@tim-yao I have updated the check to include the details link which will take you to the e2e test.
Let me know if this will fit the requirements and what the text should display in the check. eg. Should we keep the same naming convention as the other checks `dpc-sdp/ripple/e2e`

**Comment by tim-yao** [comment]
> @tim-yao I have updated the check to include the details link which will take you to the e2e test. Let me know if this will fit the requirements and what the text should display in the check. eg. Should we keep the same naming convention as the other checks `dpc-sdp/ripple/e2e`

Nice one! It looks good to me. And keep it `e2e` is ok. No need to change. Thanks!

**Comment by MarkCalvert** [comment]
Hi @tim-yao ,
I have updated the set_status workflow branch to main.
This is now ready for your review and approval.

**Comment by tim-yao** [comment]
Thanks, @MarkCalvert the set status looks good to me. But I need to make some changes on the jobs.

- remove the backend test in this workflow
- add the right docker image tag to the test job

I will create a PR from this branch soon.

**Review by steveworley — APPROVED** [review]

**Comment by MarkCalvert** [comment]
@tim-yao Do we still need this PR with these changes included in this PR? https://github.com/dpc-sdp/ripple/pull/1322

**Comment by tim-yao** [comment]
> @tim-yao Do we still need this PR with these changes included in this PR? #1322

Let 

> @tim-yao Do we still need this PR with these changes included in this PR? #1322

I have merged my PR into yours and added a initial status step as @klaukl discussed with your team.

**Review by steveworley — APPROVED** [review]

**Comment by tim-yao** [comment]
@MarkCalvert the develop reference backend has a bug that caused e2e testing not to pass, I am okay to either merge it or hold it while waiting for the backend fixed.

**Comment by tim-yao** [comment]
Hi @MarkCalvert haven't got all the tests pass yet. Let's hold it for now and I will fix it by end of this week. Cheers!

**Pull request merged**
