### PR TITLE
[SDPA-4608] : Add imageless support for CTA component

### PR DESCRIPTION
**Pull request by FleetAdmiralButter**
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4608

### Changed

1.  Add support for rendering CTA component without a Featured Image.

### Screenshots

Screenshot 2020-09-16 112905

### CODE REVIEW

**Review by tim-yao — COMMENTED** [review]
Hey @FleetAdmiralButter I guess you need to do the same changes to CTA card as well? In CMS, you can chose card or banner. https://github.com/dpc-sdp/ripple/blob/master/packages/components/Molecules/Card/CardCta.vue

**Review by dylankelly — COMMENTED** [review]
@FleetAdmiralButter I dont think we should support this - See my comment on the Jira ticket, needs design input

**Comment by dylankelly** [comment]
> @FleetAdmiralButter I dont think we should support this - See my comment on the Jira ticket, needs design input

Design thinks we should support this.

**Comment by FleetAdmiralButter** [comment]
Hey @tim-yao,

The CTACard component already works without a Featured Image, not sure if we need to make any changes?

Screenshot 2020-09-16 121007

**Review by tim-yao — APPROVED** [review]
I can see test fail is due to dev BE and search issue. Can be ignored.

**Pull request merged**
