### PR TITLE
Release v1.35.1

### PR DESCRIPTION
**Pull request by lambry**
## Motivation and Context

**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-6808

## Changed

1. New minor release to include fix for `rpl-data-list` result mapping (which is in develop), see: https://github.com/dpc-sdp/ripple/pull/1284

Release diff: https://github.com/dpc-sdp/ripple/compare/v1.35.0...release/1.35.1

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist

- [ ] I've added relevant changes to the documentation.
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] My change requires a template update for create-ripple-app.
- [ ] I have added template update script for next release.

### CODE REVIEW

**Review by dylankelly — APPROVED** [review]

**Comment by lambry** [comment]
Hey @dylankelly, do I need to worry about these failing tests before finishing the release? Seems like they always fail anyway.

Screenshot 2023-03-28 at 3 39 06 pm

#### 1.33.0 Release
Screenshot 2023-03-28 at 3 41 58 pm

**Comment by dylankelly** [comment]
> Hey @dylankelly, do I need to worry about these failing tests before finishing the release? Seems like they always fail anyway.
> 
> Screenshot 2023-03-28 at 3 39 06 pm
> 
> #### 1.33.0 Release
> Screenshot 2023-03-28 at 3 41 58 pm

Thats a question for @klaukl or @tim-yao

**Comment by tim-yao** [comment]
> > Hey @dylankelly, do I need to worry about these failing tests before finishing the release? Seems like they always fail anyway.
> > Screenshot 2023-03-28 at 3 39 06 pm
> > #### 1.33.0 Release
> > Screenshot 2023-03-28 at 3 41 58 pm
> 
> Thats a question for @klaukl or @tim-yao

Yes, we should. I see two failures, one for the promotion card and one for sitemap.xml(which is most likely a backend deployment issue that can be ignored). 
I will do a quick check to see why promotion card test failed.

**Comment by lambry** [comment]
> 

Thanks @tim-yao

**Pull request merged**
