### PR TITLE
Optimised svg icons via SVGO 

### PR DESCRIPTION
**Pull request by rubyllamadora**
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4520

### Changed

1.  Optimised Icon component's scgs `assets/img/` via svgo command

### Notes
- Custom library is one of the the culprits for the loading script https://github.com/dpc-sdp/ripple/blob/master/packages/components/Atoms/Icon/icon-library.js#L12
- We also need to minimised other websites svgs?
- Haven't spent much time to look into making `icon-library.js` better. I'm thinking of removing this as dependency in Icon.vue and adding a static Object listing of Icon names but this could be breaking change. Happy to proceed if everyone agrees.
- Any suggestions? 

### Screenshots

Comparison between `develop` and this branch
Develop: Summary total scripting time: 3187
This branch: 2957

**This branch**
iconLibrary svgo

**Develop**
iconLibrary develop

### CODE REVIEW

**Review by tim-yao — APPROVED** [review]
@rubyllamadora In my opinion, just need merge this change into https://github.com/dpc-sdp/ripple/pull/774 to update the icon paths. Other svg should still go through the webpack svgo plugin, so no need to worry I think.

**Comment by rubyllamadora** [comment]
> @rubyllamadora In my opinion, just need merge this change into #774 to update the icon paths. Other svg should still go through the webpack svgo plugin, so no need to worry I think.

Thanks @tim-yao. #774 is using JS so no need to optimise. We can probably take this as first step and will rethink of how we can handle other issues later? I avoided applying other refactor in here as there's already several file changes.

**Comment by rubyllamadora** [comment]
> > @rubyllamadora In my opinion, just need merge this change into #774 to update the icon paths. Other svg should still go through the webpack svgo plugin, so no need to worry I think.
> 

Will update #774 PR with optimised paths.

**Comment by rubyllamadora** [comment]
Closing as this has been applied to #774

**Pull request closed without merging**
