### PR TITLE
Release/1.34.0

### PR DESCRIPTION
**Pull request by rubyllamadora**
## Motivation and Context

**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-

## Changed

1.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist

- [ ] I've added relevant changes to the documentation.
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] My change requires a template update for create-ripple-app.
- [ ] I have added template update script for next release.

### CODE REVIEW

**Comment by rubyllamadora** [comment]
@MdNadimHossain this should be ok to merge?

**Comment by MdNadimHossain** [comment]
> @MdNadimHossain this should be ok to merge?
Yes, can you have a quick review please before merging :D

**Comment by rubyllamadora** [comment]
Looks fine @MdNadimHossain. Shall we sync with develop? It has version update with cheerio plugin. Or revert the latest change in develop? Did we have something like this happen before?

**Review by MdNadimHossain — APPROVED** [review]

**Comment by rubyllamadora** [comment]
Search endpoint is currently not working thus smoke tests failed. Merging.

**Pull request merged**
