### PR TITLE
[SDPA-4893] Add max-width to callout markup

### PR DESCRIPTION
**Pull request by Yuuupie**
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-4893

### Changed

1.  Added max-width to callout markup

### Screenshots

**Before:**
image

**After:**
image

### CODE REVIEW

**Review by tim-yao — APPROVED** [review]

**Comment by tim-yao** [comment]
Hey @Yuuupie I put don't merge label for now. Need to wait we merge release branch back first. Thanks!

**Comment by Yuuupie** [comment]
@tim-yao Would this need QA before merging?

**Comment by tim-yao** [comment]
> @tim-yao Would this need QA before merging?

@Yuuupie Yes

**Comment by Yuuupie** [comment]
Hey @tim-yao , is this fine to merge now or do we still need to wait for the release branch?

**Comment by tim-yao** [comment]
> Hey @tim-yao , is this fine to merge now or do we still need to wait for the release branch?

@Yuuupie I just updated this branch, you can merge it when CI test passed. Thanks!

**Pull request merged**
